# Generated by Django 5.0.6 on 2024-06-13 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
            ],
        ),
        migrations.CreateModel(
            name='TypePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CL', 'Одежда'), ('EL', 'Электроника'), ('VR', 'Разное')], max_length=2, verbose_name='Тип посылки')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Вес в кг')),
                ('cost_in_usd', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Стоимость в $')),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True, verbose_name='Стоимость доставки в ₽')),
                ('delivery_company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='package.deliverycompany')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session', verbose_name='Id сессии пользователя')),
                ('type_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='package.typepackage', verbose_name='Тип посылки')),
            ],
        ),
    ]
